# Generated by Django 5.2.4 on 2025-08-11 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areacode', models.IntegerField(help_text='Unique numeric identifier for the area (1-9999)', unique=True)),
                ('areaname', models.CharField(help_text='Descriptive name for the operational area', max_length=100)),
                ('area_description', models.TextField(blank=True, help_text="Additional details about the area's purpose or characteristics", null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], default='active', help_text='Current operational status of the area', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'db_table': 'areas',
                'ordering': ['areacode'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.IntegerField(blank=True, help_text='Auto-generated if new', null=True, unique=True)),
                ('supplier_name', models.CharField(help_text='Official registered business name', max_length=200)),
                ('supplier_short_name', models.CharField(blank=True, help_text='Optional short name or alias', max_length=50, null=True)),
                ('contact_person_name', models.CharField(help_text='Main point of contact at the supplier', max_length=100)),
                ('contact_email', models.EmailField(help_text='Primary email address', max_length=254)),
                ('contact_phone', models.CharField(help_text='Primary contact phone number', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?[\\d\\s\\-\\(\\)]+$')])),
                ('contact_mobile', models.CharField(blank=True, help_text='Mobile/secondary contact number', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number', regex='^\\+?[\\d\\s\\-\\(\\)]+$')])),
                ('business_type', models.CharField(choices=[('manufacturer', 'Manufacturer'), ('distributor', 'Distributor'), ('wholesaler', 'Wholesaler'), ('retailer', 'Retailer'), ('service_provider', 'Service Provider'), ('contractor', 'Contractor'), ('consultant', 'Consultant'), ('other', 'Other')], help_text='Type of business', max_length=20)),
                ('tax_id', models.CharField(blank=True, help_text='Tax identification or VAT number', max_length=50, null=True)),
                ('registration_number', models.CharField(blank=True, help_text='Official business registration number', max_length=50, null=True)),
                ('address_line1', models.CharField(help_text='Street address', max_length=200)),
                ('address_line2', models.CharField(blank=True, help_text='Apartment, suite, etc.', max_length=200, null=True)),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('state_province', models.CharField(help_text='State or Province', max_length=100)),
                ('postal_code', models.CharField(help_text='ZIP/Postal Code', max_length=20)),
                ('country', models.CharField(default='United States', help_text='Country', max_length=100)),
                ('payment_terms', models.CharField(choices=[('net_15', 'Net 15'), ('net_30', 'Net 30'), ('net_45', 'Net 45'), ('net_60', 'Net 60'), ('cod', 'Cash on Delivery'), ('prepaid', 'Prepaid')], default='net_30', help_text='Payment terms', max_length=20)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum credit limit in USD', max_digits=12, null=True)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('JPY', 'Japanese Yen')], default='USD', help_text='Preferred currency', max_length=3)),
                ('website', models.URLField(blank=True, help_text='Website URL', null=True)),
                ('notes', models.TextField(blank=True, help_text='Any additional information about the supplier', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending_approval', 'Pending Approval')], default='active', help_text='Supplier status', max_length=20)),
                ('is_preferred', models.BooleanField(default=False, help_text='Preferred supplier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'db_table': 'suppliers',
                'ordering': ['supplier_name'],
            },
        ),
    ]
