# Generated by Django 5.2.4 on 2025-08-11 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
    ]
