# Generated by Django 5.2.4 on 2025-08-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_auto_20250811_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='city',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='contact_mobile',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='credit_limit',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='state_province',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='supplier_short_name',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='tax_id',
        ),
        migrations.AddField(
            model_name='supplier',
            name='ntn_number',
            field=models.CharField(blank=True, help_text='National Tax Number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('JPY', 'Japanese Yen'), ('PKR', 'Pakistani Rupees')], default='USD', help_text='Preferred currency', max_length=3),
        ),
    ]
