# Generated by Django 5.2.4 on 2025-08-15 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_remove_supplier_address_line1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(blank=True, help_text='Auto-generated if new', null=True, unique=True)),
                ('customer_name', models.CharField(help_text='Official registered business or individual name', max_length=200)),
                ('customer_type', models.CharField(choices=[('individual', 'Individual'), ('business', 'Business'), ('government', 'Government'), ('non_profit', 'Non-Profit')], help_text='Type of customer', max_length=20)),
                ('contact_person_name', models.CharField(help_text='Main point of contact for the customer', max_length=100)),
                ('contact_email', models.EmailField(help_text='Primary email address', max_length=254)),
                ('contact_phone', models.CharField(help_text='Primary contact phone number', max_length=12, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?[\\d\\s\\-\\(\\)]+$')])),
                ('address_line1', models.CharField(help_text='Street address', max_length=200)),
                ('address_line2', models.CharField(blank=True, help_text='Apartment, suite, etc.', max_length=200, null=True)),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('state_province', models.CharField(help_text='State or Province', max_length=100)),
                ('postal_code', models.CharField(help_text='Postal or ZIP code', max_length=20)),
                ('country', models.CharField(default='Pakistan', help_text='Country', max_length=100)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum credit limit for this customer', max_digits=10, null=True)),
                ('payment_terms', models.CharField(choices=[('net_15', 'Net 15'), ('net_30', 'Net 30'), ('net_45', 'Net 45'), ('net_60', 'Net 60'), ('cod', 'Cash on Delivery'), ('prepaid', 'Prepaid')], default='net_30', help_text='Payment terms', max_length=20)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('JPY', 'Japanese Yen'), ('PKR', 'Pakistani Rupees')], default='PKR', help_text='Preferred currency', max_length=3)),
                ('website', models.URLField(blank=True, help_text='Website URL', null=True)),
                ('notes', models.TextField(blank=True, help_text='Any additional information about the customer', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending_approval', 'Pending Approval')], default='active', help_text='Customer status', max_length=20)),
                ('is_preferred', models.BooleanField(default=False, help_text='Preferred customer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
                'ordering': ['customer_name'],
            },
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_phone',
            field=models.CharField(help_text='Primary contact phone number', max_length=12, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?[\\d\\s\\-\\(\\)]+$')]),
        ),
    ]
