# Generated by Django 5.2.4 on 2025-08-15 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_customer_alter_supplier_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address_line2',
        ),
    ]
