# Generated by Django 5.2.4 on 2025-08-15 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_remove_customer_address_line1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='credit_limit',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='state_province',
        ),
    ]
