# Generated by Django 5.2.4 on 2025-09-07 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_remove_customer_city_remove_customer_credit_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateField(help_text='Date of purchase order')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total purchase amount', max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('JPY', 'Japanese Yen'), ('PKR', 'Pakistani Rupees')], default='PKR', help_text='Currency for the purchase', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('ordered', 'Ordered'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', help_text='Current status of the purchase', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the purchase', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(help_text='Supplier for this purchase', on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='erp.supplier')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'db_table': 'purchases',
                'ordering': ['-purchase_date'],
            },
        ),
    ]
