# Generated by Django 5.2.4 on 2025-09-08 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_purchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AreaForm',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
