# Generated by Django 5.2.4 on 2025-09-08 08:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areacode', models.IntegerField(help_text='Unique numeric identifier for the area (1-9999)', unique=True)),
                ('areaname', models.CharField(help_text='Descriptive name for the operational area', max_length=100)),
                ('area_description', models.TextField(blank=True, help_text="Additional details about the area's purpose or characteristics", null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], default='active', help_text='Current operational status of the area', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'db_table': 'areas',
                'ordering': ['areacode'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(blank=True, help_text='Auto-generated if new', null=True, unique=True)),
                ('customer_name', models.CharField(help_text='Official registered business or individual name', max_length=200)),
                ('customer_type', models.CharField(choices=[('individual', 'Individual'), ('business', 'Business'), ('government', 'Government'), ('non_profit', 'Non-Profit')], help_text='Type of customer', max_length=20)),
                ('contact_person_name', models.CharField(help_text='Main point of contact for the customer', max_length=100)),
                ('contact_email', models.EmailField(help_text='Primary email address', max_length=254)),
                ('contact_phone', models.CharField(help_text='Primary contact phone number', max_length=12, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?[\\d\\s\\-\\(\\)]+$')])),
                ('country', models.CharField(default='Pakistan', help_text='Country', max_length=100)),
                ('payment_terms', models.CharField(choices=[('net_15', 'Net 15'), ('net_30', 'Net 30'), ('net_45', 'Net 45'), ('net_60', 'Net 60'), ('cod', 'Cash on Delivery'), ('prepaid', 'Prepaid')], default='net_30', help_text='Payment terms', max_length=20)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('JPY', 'Japanese Yen'), ('PKR', 'Pakistani Rupees')], default='PKR', help_text='Preferred currency', max_length=3)),
                ('website', models.URLField(blank=True, help_text='Website URL', null=True)),
                ('notes', models.TextField(blank=True, help_text='Any additional information about the customer', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending_approval', 'Pending Approval')], default='active', help_text='Customer status', max_length=20)),
                ('is_preferred', models.BooleanField(default=False, help_text='Preferred customer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
                'ordering': ['customer_name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.IntegerField(blank=True, help_text='Auto-generated if new', null=True, unique=True)),
                ('supplier_name', models.CharField(help_text='Official registered business name', max_length=200)),
                ('contact_person_name', models.CharField(help_text='Main point of contact at the supplier', max_length=100)),
                ('contact_email', models.EmailField(help_text='Primary email address', max_length=254)),
                ('contact_phone', models.CharField(help_text='Primary contact phone number', max_length=12, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?[\\d\\s\\-\\(\\)]+$')])),
                ('business_type', models.CharField(choices=[('manufacturer', 'Manufacturer'), ('distributor', 'Distributor'), ('wholesaler', 'Wholesaler'), ('retailer', 'Retailer'), ('service_provider', 'Service Provider'), ('contractor', 'Contractor'), ('consultant', 'Consultant'), ('other', 'Other')], help_text='Type of business', max_length=20)),
                ('ntn_number', models.CharField(blank=True, help_text='National Tax Number', max_length=50, null=True)),
                ('country', models.CharField(default='United States', help_text='Country', max_length=100)),
                ('payment_terms', models.CharField(choices=[('net_15', 'Net 15'), ('net_30', 'Net 30'), ('net_45', 'Net 45'), ('net_60', 'Net 60'), ('cod', 'Cash on Delivery'), ('prepaid', 'Prepaid')], default='net_30', help_text='Payment terms', max_length=20)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('JPY', 'Japanese Yen'), ('PKR', 'Pakistani Rupees')], default='USD', help_text='Preferred currency', max_length=3)),
                ('website', models.URLField(blank=True, help_text='Website URL', null=True)),
                ('notes', models.TextField(blank=True, help_text='Any additional information about the supplier', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending_approval', 'Pending Approval')], default='active', help_text='Supplier status', max_length=20)),
                ('is_preferred', models.BooleanField(default=False, help_text='Preferred supplier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'db_table': 'suppliers',
                'ordering': ['supplier_name'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateField(help_text='Date of purchase order')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total purchase amount', max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('JPY', 'Japanese Yen'), ('PKR', 'Pakistani Rupees')], default='PKR', help_text='Currency for the purchase', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('ordered', 'Ordered'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', help_text='Current status of the purchase', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the purchase', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(help_text='Supplier for this purchase', on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='inventory.supplier')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'db_table': 'purchases',
                'ordering': ['-purchase_date'],
            },
        ),
    ]
