# Generated by Django 5.2.4 on 2025-09-11 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_invcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50, unique=True)),
                ('item_name', models.CharField(max_length=250)),
                ('specification', models.CharField()),
                ('salestax_type', models.CharField(choices=[('GST', 'GST'), ('VAT', 'VAT'), ('EXEMPT', 'Exempt')], max_length=50)),
                ('unit_of_measure', models.CharField(max_length=20)),
                ('std_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('important', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.itemdefinition')),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.invcategory')),
            ],
        ),
    ]
