# Generated by Django 5.2.4 on 2025-09-11 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_itemdefinition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(max_length=50, unique=True)),
                ('requisition_by', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.departmentdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50, unique=True)),
                ('po_date', models.DateField()),
                ('po_type', models.CharField(max_length=50)),
                ('station_code', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('terms_conditions', models.TextField(blank=True, null=True)),
                ('ref_no', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_at', models.CharField(max_length=250)),
                ('order_by', models.CharField(max_length=100)),
                ('condition', models.TextField(blank=True, null=True)),
                ('freight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.requisition')),
            ],
        ),
    ]
