# Generated by Django 5.2.4 on 2025-09-11 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_requisition_purchaseorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField()),
                ('nature', models.CharField(choices=[('Issue', 'Issue'), ('Return', 'Return')], max_length=30)),
                ('lot_no', models.CharField(max_length=30, verbose_name='Lot No')),
                ('dc_no', models.CharField(max_length=30, verbose_name='D/C No')),
                ('material', models.CharField(max_length=200, null=True, verbose_name='Material')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.areaform')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.customer')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.departmentdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='LotTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_no', models.CharField(max_length=20, unique=True, verbose_name='Document No')),
                ('date', models.DateField()),
                ('gray_receipt_no', models.CharField(max_length=30, verbose_name='Gray Receipt No')),
                ('dc_no', models.CharField(max_length=30, verbose_name='D/C No')),
                ('lot_no', models.CharField(max_length=30, verbose_name='Lot No')),
                ('nature', models.CharField(choices=[('Dyeing', 'Dyeing'), ('Bleaching', 'Bleaching'), ('Finishing', 'Finishing')], max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(max_length=20, unique=True)),
                ('transaction_type', models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit'), ('Return', 'Return')], max_length=20)),
                ('transaction_date', models.DateField()),
                ('bill_no', models.CharField(max_length=50)),
                ('st_inv_no', models.CharField(max_length=50, verbose_name='S/T Inv. No')),
                ('bilty_no', models.CharField(max_length=50)),
                ('days', models.PositiveIntegerField(help_text='Number of credit days or delivery days')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(max_length=50, unique=True)),
                ('transaction_date', models.DateField()),
                ('nature', models.CharField(max_length=100)),
                ('delivery_challan_no', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('grir', models.CharField(max_length=100)),
                ('gpi_status', models.CharField(choices=[('Pending', 'pending'), ('Approved', 'approved'), ('Rejected', 'rejected')], default='Pending', max_length=50)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.areaform')),
                ('client_po', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_client_po', to='inventory.purchaseorder')),
                ('gpo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_gpo', to='inventory.purchaseorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier')),
            ],
        ),
    ]
