# Generated by Django 5.2.4 on 2025-09-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_issuetransaction_lottransaction_purchasevoucher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuetransaction',
            name='material',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
