# Generated by Django 5.2.4 on 2025-09-11 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_issuetransaction_material'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuetransaction',
            options={'verbose_name': 'Issue Transaction', 'verbose_name_plural': 'Issue Transactions'},
        ),
        migrations.AlterModelOptions(
            name='itemdefinition',
            options={'verbose_name': 'Item Definition', 'verbose_name_plural': 'Item Definition'},
        ),
        migrations.AlterModelOptions(
            name='lottransaction',
            options={'verbose_name': 'Lor Transaction', 'verbose_name_plural': 'Lot Transactions'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'verbose_name': 'Purchase Order', 'verbose_name_plural': 'Purchase Orders'},
        ),
        migrations.AlterModelOptions(
            name='purchasevoucher',
            options={'verbose_name': 'Purchase Voucher', 'verbose_name_plural': 'Purchase Vouchers'},
        ),
        migrations.AlterModelOptions(
            name='receipttransaction',
            options={'verbose_name': 'Receipt Transaction', 'verbose_name_plural': 'Receipt Transactions'},
        ),
        migrations.AlterModelOptions(
            name='requisition',
            options={'verbose_name': 'Requisition', 'verbose_name_plural': 'Requisition'},
        ),
        migrations.AlterModelTable(
            name='issuetransaction',
            table='issue_transaction',
        ),
        migrations.AlterModelTable(
            name='itemdefinition',
            table='item_definition',
        ),
        migrations.AlterModelTable(
            name='lottransaction',
            table='lot_transaction',
        ),
        migrations.AlterModelTable(
            name='purchaseorder',
            table='purchase_order',
        ),
        migrations.AlterModelTable(
            name='purchasevoucher',
            table='purchase_voucher',
        ),
        migrations.AlterModelTable(
            name='receipttransaction',
            table='receipt_transaction',
        ),
        migrations.AlterModelTable(
            name='requisition',
            table='requisition',
        ),
    ]
