# Generated by Django 5.2.4 on 2025-11-19 17:08

import django.db.models.deletion
from django.db import migrations, models


def add_fields_if_not_exist(apps, schema_editor):
    """Add fields only if they don't already exist"""
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Check and add purchase_order fields
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='purchase_order' AND column_name='amount'
        """)
        if not cursor.fetchone():
            cursor.execute("""
                ALTER TABLE purchase_order 
                ADD COLUMN amount NUMERIC(12, 2) NULL
            """)
        
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='purchase_order' AND column_name='discount'
        """)
        if not cursor.fetchone():
            cursor.execute("""
                ALTER TABLE purchase_order 
                ADD COLUMN discount NUMERIC(10, 2) NULL
            """)
        
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='purchase_order' AND column_name='quantity'
        """)
        if not cursor.fetchone():
            cursor.execute("""
                ALTER TABLE purchase_order 
                ADD COLUMN quantity NUMERIC(10, 2) NULL
            """)
        
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='purchase_order' AND column_name='rate'
        """)
        if not cursor.fetchone():
            cursor.execute("""
                ALTER TABLE purchase_order 
                ADD COLUMN rate NUMERIC(10, 2) NULL
            """)
        
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='purchase_order' AND column_name='requisition_number'
        """)
        if not cursor.fetchone():
            cursor.execute("""
                ALTER TABLE purchase_order 
                ADD COLUMN requisition_number VARCHAR(50) NULL
            """)
        
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='purchase_order' AND column_name='sales_tax'
        """)
        if not cursor.fetchone():
            cursor.execute("""
                ALTER TABLE purchase_order 
                ADD COLUMN sales_tax NUMERIC(10, 2) NULL
            """)
        
        # Check and add receipt_transaction fields
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='receipt_transaction' AND column_name='amount'
        """)
        if not cursor.fetchone():
            cursor.execute("""
                ALTER TABLE receipt_transaction 
                ADD COLUMN amount NUMERIC(12, 2) NULL
            """)
        
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='receipt_transaction' AND column_name='item_id'
        """)
        if not cursor.fetchone():
            cursor.execute("""
                ALTER TABLE receipt_transaction 
                ADD COLUMN item_id INTEGER NULL 
                REFERENCES item_definition(id) ON DELETE SET NULL
            """)
        
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='receipt_transaction' AND column_name='po_id'
        """)
        if not cursor.fetchone():
            cursor.execute("""
                ALTER TABLE receipt_transaction 
                ADD COLUMN po_id INTEGER NULL 
                REFERENCES purchase_order(id) ON DELETE SET NULL
            """)
        
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='receipt_transaction' AND column_name='quantity'
        """)
        if not cursor.fetchone():
            cursor.execute("""
                ALTER TABLE receipt_transaction 
                ADD COLUMN quantity NUMERIC(10, 2) NULL
            """)
        
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='receipt_transaction' AND column_name='rate'
        """)
        if not cursor.fetchone():
            cursor.execute("""
                ALTER TABLE receipt_transaction 
                ADD COLUMN rate NUMERIC(10, 2) NULL
            """)
        
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='receipt_transaction' AND column_name='st'
        """)
        if not cursor.fetchone():
            cursor.execute("""
                ALTER TABLE receipt_transaction 
                ADD COLUMN st NUMERIC(10, 2) NULL
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_issuetransaction_options_and_more'),
    ]

    operations = [
        migrations.RunPython(add_fields_if_not_exist, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='receipttransaction',
            options={'verbose_name': 'GRN', 'verbose_name_plural': 'GRNs'},
        ),
        migrations.AlterModelTable(
            name='receipttransaction',
            table='grn',
        ),
    ]
