# Generated by Django 5.2.4 on 2025-11-19 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_receipttransaction_options_and_more'),
    ]

    operations = [
    ]
