# Generated by Django 5.2.4 on 2025-11-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_purchaseorder_amount_purchaseorder_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaform',
            name='area_code',
            field=models.CharField(blank=True, help_text='Auto-generated code (e.g., AREA-0001)', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(blank=True, help_text='Auto-generated code (e.g., CUST-0001)', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_code',
            field=models.CharField(blank=True, help_text='Auto-generated code (e.g., SUP-0001)', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='itemdefinition',
            name='specification',
            field=models.CharField(blank=True, null=True),
        ),
    ]
