# Generated by Django 5.2.4 on 2025-11-22 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_areaform_area_code_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='station_code',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.areaform'),
        ),
    ]
